name: storyapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter Dependencies
  cupertino_icons: ^1.0.2
  flutter_platform_widgets: ^7.0.0
  
  # UI and Widgets
  camera: ^0.10.5+9
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  pinput: ^4.0.0
  carousel_slider: ^4.2.1
  pull_to_refresh: ^2.0.0
  flutter_image_compress: ^2.2.0
  bot_toast: ^4.1.3

  # State Management
  provider: ^6.1.2
  stacked: ^3.4.2
  get_it: ^7.6.7

  # Firebase
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  firebase_storage: ^11.7.4

  # Networking
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.2

  # Utilities
  media_picker_widget: ^1.0.7
  libphonenumber_plugin: ^0.3.3
  logging: ^1.2.0
  device_info_plus: ^10.1.0
  built_value: ^8.9.2
  get_storage: ^2.1.1
  mime: ^1.0.5
  receive_sharing_intent: ^1.8.0
  hive: ^2.2.3
  json_annotation: ^4.9.0

  # Localization
  easy_localization: ^3.0.7
  device_preview: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0

  # Route management
  auto_route: ^7.9.2

dependency_overrides:
  # Dependency Overrides
  photo_manager: ^3.0.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  built_value_generator: ^8.7.0
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  easy_localization_generator: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700

    - family: NotoSansGujarati
      fonts:
        - asset: assets/fonts/NotoSans/NotoSansGujarati-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans/NotoSansGujarati-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans/NotoSansGujarati-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans/NotoSansGujarati-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSansGujarati-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans/NotoSansGujarati-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans/NotoSansGujarati-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSansGujarati-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans/NotoSansGujarati-Black.ttf
          weight: 900